// Major cities and regions that should override location detection
export const KNOWN_LOCATIONS = [
  // Major US cities
  "new york",
  "new york city",
  "nyc",
  "manhattan",
  "brooklyn",
  "queens",
  "bronx",
  "staten island",
  "los angeles",
  "la",
  "hollywood",
  "beverly hills",
  "santa monica",
  "chicago",
  "houston",
  "phoenix",
  "philadelphia",
  "philly",
  "san antonio",
  "san diego",
  "dallas",
  "san jose",
  "austin",
  "jacksonville",
  "fort worth",
  "columbus",
  "charlotte",
  "san francisco",
  "sf",
  "bay area",
  "indianapolis",
  "seattle",
  "denver",
  "washington",
  "washington dc",
  "dc",
  "boston",
  "el paso",
  "detroit",
  "nashville",
  "portland",
  "memphis",
  "oklahoma city",
  "las vegas",
  "vegas",
  "louisville",
  "baltimore",
  "milwaukee",
  "albuquerque",
  "tucson",
  "fresno",
  "mesa",
  "kansas city",
  "atlanta",
  "omaha",
  "raleigh",
  "miami",
  "long beach",
  "virginia beach",
  "oakland",
  "minneapolis",
  "tulsa",
  "tampa",
  "arlington",
  "honolulu",
  "anchorage",

  // Major International cities - Europe
  "london",
  "paris",
  "berlin",
  "madrid",
  "rome",
  "amsterdam",
  "vienna",
  "prague",
  "budapest",
  "warsaw",
  "stockholm",
  "oslo",
  "copenhagen",
  "helsinki",
  "dublin",
  "zurich",
  "barcelona",
  "milan",
  "moscow",
  "istanbul",
  "athens",
  "lisbon",
  "brussels",
  "munich",
  "hamburg",
  "cologne",
  "frankfurt",
  "stuttgart",
  "düsseldorf",
  "dusseldorf",
  "edinburgh",
  "glasgow",
  "manchester",
  "birmingham",
  "liverpool",
  "leeds",
  "sheffield",
  "bristol",
  "cardiff",
  "belfast",
  "marseille",
  "lyon",
  "toulouse",
  "nice",
  "nantes",
  "strasbourg",
  "montpellier",
  "bordeaux",
  "lille",
  "rennes",
  "reims",
  "le havre",
  "saint-étienne",
  "toulon",
  "grenoble",
  "dijon",
  "angers",
  "nîmes",
  "villeurbanne",
  "saint-denis",
  "le mans",
  "aix-en-provence",
  "clermont-ferrand",
  "brest",
  "limoges",
  "tours",
  "amiens",
  "perpignan",
  "metz",
  "besançon",
  "boulogne-billancourt",
  "orléans",
  "mulhouse",
  "rouen",
  "saint-paul",
  "argenteuil",
  "caen",
  "nancy",
  "tourcoing",
  "roubaix",
  "nanterre",
  "avignon",
  "créteil",
  "dunkerque",
  "poitiers",
  "versailles",
  "courbevoie",
  "fort-de-france",
  "vitry-sur-seine",
  "saint-pierre",
  "colombes",
  "aulnay-sous-bois",
  "asnières-sur-seine",
  "rueil-malmaison",
  "antibes",
  "saint-maur-des-fossés",
  "champigny-sur-marne",
  "la rochelle",
  "aubervilliers",
  "calais",
  "cannes",
  "le tampon",
  "béziers",
  "colmar",
  "bourges",
  "drancy",
  "mérignac",
  "saint-nazaire",
  "valence",
  "ajaccio",
  "issy-les-moulineaux",
  "villeurban",
  "levallois-perret",
  "noumea",
  "quimper",
  "la seyne-sur-mer",
  "antony",
  "troyes",
  "neuilly-sur-seine",
  "sarcelles",
  "les abymes",
  "vénissieux",
  "clichy",
  "lorient",
  "pessac",
  "ivry-sur-seine",
  "cergy",
  "saint-ouen",
  "chambéry",
  "niort",
  "montauban",
  "saint-quentin",
  "villejuif",
  "hyères",
  "beauvais",
  "cholet",
  "vannes",
  "laval",
  "saint-brieuc",
  "pau",
  "bondy",
  "fontenay-sous-bois",
  "clamart",
  "bourg-en-bresse",
  "chelles",
  "chartres",
  "évry",
  "épinal",
  "meaux",
  "plaisir",
  "châlons-en-champagne",
  "saint-malo",
  "châteauroux",
  "caluire-et-cuire",
  "boulogne-sur-mer",
  "saint-priest",
  "rosny-sous-bois",
  "saint-raphael",
  "albi",
  "belfort",
  "montrouge",
  "choisy-le-roi",
  "saint-germain-en-laye",
  "matoury",
  "echirolles",
  "vincennes",
  "alès",
  "corbeil-essonnes",
  "blois",
  "villefranche-sur-saône",
  "livry-gargan",
  "calais",
  "saint-chamond",
  "massy",
  "périgueux",
  "saint-louis",
  "garges-lès-gonesse",
  "brive-la-gaillarde",
  "vaulx-en-velin",
  "montpellier",
  "carcassonne",
  "agen",
  "alfortville",
  "bastia",
  "bagneux",
  "saint-martin-d'hères",
  "pontault-combault",
  "chatou",
  "tremblay-en-france",
  "stains",
  "montluçon",
  "bagnolet",
  "beaune",
  "châtillon",
  "draguignan",
  "cherbourg-en-cotentin",
  "franconville",
  "poissy",
  "gonesse",
  "champs-sur-marne",
  "melun",
  "cambrai",
  "chelles",
  "châtenay-malabry",
  "wattrelos",
  "savigny-sur-orge",
  "saint-étienne-du-rouvray",
  "sainte-geneviève-des-bois",
  "martigues",
  "gennevilliers",
  "salon-de-provence",
  "châlons-en-champagne",
  "reze",
  "grasse",
  "castres",
  "châteauroux",
  "saint-denis",
  "arles",
  "pontoise",
  "le blanc-mesnil",
  "thionville",
  "saint-martin",
  "évreux",
  "istres",
  "villeneuve-saint-georges",
  "epinay-sur-seine",
  "agde",
  "guyancourt",
  "mont-de-marsan",
  "saint-sebastien-sur-loire",
  "mantes-la-jolie",
  "meudon",
  "bayonne",
  "sotteville-lès-rouen",
  "garges-les-gonesse",
  "bron",
  "soissons",
  "saint-amand-les-eaux",
  "paray-vieille-poste",
  "gap",
  "fréjus",
  "bayonne",
  "angouleme",
  "saint-benoît",
  "châtou",
  "lingolsheim",
  "montfermeil",
  "boissy-saint-léger",
  "château-thierry",
  "ozoir-la-ferrière",
  "villiers-sur-marne",
  "thonon-les-bains",
  "monthey",
  "saint-leu",
  "villemomble",
  "houilles",
  "romainville",
  "le perreux-sur-marne",
  "conflans-sainte-honorine",
  "rosny-sous-bois",
  "cagnes-sur-mer",
  "la ciotat",
  "saint-ouen-l'aumône",
  "lambersart",
  "montigny-lès-metz",
  "villiers-le-bel",
  "palaiseau",
  "nogent-sur-marne",
  "châtenay-malabry",
  "villeneuve-d'ascq",
  "saint-cloud",
  "bagneux",
  "yerres",
  "villeneuve-la-garenne",
  "sainte-foy-lès-lyon",
  "montigny-le-bretonneux",
  "les lilas",
  "les pavillons-sous-bois",
  "courbevoie",
  "bagnolet",
  "saint-gratien",
  "brunoy",
  "le raincy",
  "fresnes",
  "bois-colombes",
  "l'haÿ-les-roses",
  "charenton-le-pont",
  "maisons-laffitte",
  "malakoff",
  "fontenay-aux-roses",
  "sceaux",
  "châtillon",
  "vanves",
  "montrouge",
  "saint-mandé",
  "issy-les-moulineaux",
  "gentilly",
  "arcueil",
  "cachan",
  "le kremlin-bicêtre",
  "ivry-sur-seine",
  "villejuif",
  "vitry-sur-seine",
  "choisy-le-roi",
  "thiais",
  "orly",
  "chevilly-larue",
  "rungis",
  "fresnes",
  "antony",
  "bourg-la-reine",
  "sceaux",
  "châtenay-malabry",
  "le plessis-robinson",
  "fontenay-aux-roses",
  "malakoff",
  "montrouge",
  "bagneux",
  "clamart",
  "issy-les-moulineaux",
  "vanves",
  "châtillon",
  "meudon",
  "bellevue",
  "sèvres",
  "ville-d'avray",
  "chaville",
  "vélizy-villacoublay",
  "viroflay",
  "igny",
  "bièvres",
  "jouy-en-josas",
  "les loges-en-josas",
  "saint-cyr-l'école",
  "versailles",
  "le chesnay",
  "rocquencourt",
  "bailly",
  "noisy-le-roi",
  "rennemoulin",
  "davron",
  "saint-rémy-lès-chevreuse",
  "gif-sur-yvette",
  "saclay",
  "orsay",
  "palaiseau",
  "châtenay-malabry",
  "sceaux",
  "antony",
  "wissous",
  "verrières-le-buisson",
  "massy",
  "chilly-mazarin",
  "longjumeau",
  "saulx-les-chartreux",
  "les ulis",
  "orsay",
  "bures-sur-yvette",
  "gometz-le-châtel",
  "limours",
  "forges-les-bains",
  "les molières",
  "pecqueuse",
  "cernay-la-ville",
  "auffargis",
  "saint-rémy-lès-chevreuse",
  "chevreuse",
  "choisel",
  "dampierre-en-yvelines",
  "senlisse",
  "clairefontaine-en-yvelines",
  "rambouillet",
  "gazeran",
  "poigny-la-forêt",
  "le perray-en-yvelines",
  "les bréviaires",
  "bonnelles",
  "bullion",
  "cernay-la-ville",
  "saint-arnoult-en-yvelines",
  "rochefort-en-yvelines",
  "saint-martin-de-bréthencourt",
  "ablis",
  "orphin",
  "sonchamp",
  "saint-hilarion",
  "paray-douaville",
  "neauphle-le-château",
  "villiers-le-mahieu",
  "thoiry",
  "beynes",
  "neauphle-le-vieux",
  "maule",
  "aulnay-sur-mauldre",
  "montainville",
  "galluis",
  "bazoches-sur-guyonne",
  "saint-rémy-l'honoré",
  "les clayes-sous-bois",
  "plaisir",
  "élancourt",
  "trappes",
  "montigny-le-bretonneux",
  "saint-quentin-en-yvelines",
  "guyancourt",
  "voisins-le-bretonneux",
  "magny-les-hameaux",
  "toussus-le-noble",
  "châteaufort",
  "le mesnil-saint-denis",
  "dampierre-en-yvelines",
  "chevreuse",
  "saint-forget",
  "milon-la-chapelle",
  "saint-lambert",
  "cernay-la-ville",
  "senlisse",
  "saint-rémy-lès-chevreuse",

  // Asia-Pacific
  "tokyo",
  "osaka",
  "kyoto",
  "nagoya",
  "sapporo",
  "fukuoka",
  "kobe",
  "yokohama",
  "sendai",
  "hiroshima",
  "beijing",
  "shanghai",
  "guangzhou",
  "shenzhen",
  "tianjin",
  "wuhan",
  "xi'an",
  "chengdu",
  "nanjing",
  "chongqing",
  "hangzhou",
  "qingdao",
  "dalian",
  "mumbai",
  "delhi",
  "bangalore",
  "hyderabad",
  "ahmedabad",
  "chennai",
  "kolkata",
  "pune",
  "jaipur",
  "lucknow",
  "kanpur",
  "nagpur",
  "indore",
  "thane",
  "bhopal",
  "visakhapatnam",
  "pimpri-chinchwad",
  "patna",
  "vadodara",
  "ghaziabad",
  "ludhiana",
  "agra",
  "nashik",
  "faridabad",
  "meerut",
  "rajkot",
  "kalyan-dombivali",
  "vasai-virar",
  "varanasi",
  "srinagar",
  "aurangabad",
  "dhanbad",
  "amritsar",
  "navi mumbai",
  "allahabad",
  "ranchi",
  "howrah",
  "coimbatore",
  "jabalpur",
  "gwalior",
  "vijayawada",
  "jodhpur",
  "madurai",
  "raipur",
  "kota",
  "guwahati",
  "chandigarh",
  "solapur",
  "hubli-dharwad",
  "bareilly",
  "moradabad",
  "mysore",
  "gurgaon",
  "aligarh",
  "jalandhar",
  "tiruchirappalli",
  "bhubaneswar",
  "salem",
  "warangal",
  "mira-bhayandar",
  "thiruvananthapuram",
  "bhiwandi",
  "saharanpur",
  "guntur",
  "amravati",
  "bikaner",
  "noida",
  "jamshedpur",
  "bhilai nagar",
  "cuttack",
  "firozabad",
  "kochi",
  "bhavnagar",
  "dehradun",
  "durgapur",
  "asansol",
  "nanded-waghala",
  "kolapur",
  "ajmer",
  "gulbarga",
  "jamnagar",
  "ujjain",
  "loni",
  "siliguri",
  "jhansi",
  "ulhasnagar",
  "nellore",
  "jammu",
  "sangli-miraj & kupwad",
  "belgaum",
  "mangalore",
  "ambattur",
  "tirunelveli",
  "malegaon",
  "gaya",
  "jalgaon",
  "udaipur",
  "maheshtala",
  "seoul",
  "busan",
  "incheon",
  "daegu",
  "daejeon",
  "gwangju",
  "suwon",
  "ulsan",
  "changwon",
  "goyang",
  "yongin",
  "seongnam",
  "bucheon",
  "ansan",
  "cheongju",
  "jeonju",
  "anyang",
  "cheonan",
  "pohang",
  "uijeongbu",
  "changwon",
  "jeju",
  "singapore",
  "kuala lumpur",
  "george town",
  "ipoh",
  "johor bahru",
  "petaling jaya",
  "shah alam",
  "kota kinabalu",
  "klang",
  "subang jaya",
  "selayang",
  "malacca city",
  "sandakan",
  "seremban",
  "kuantan",
  "tawau",
  "iskandar puteri",
  "ampang jaya",
  "kuala terengganu",
  "sepang",
  "kulim",
  "miri",
  "pasir gudang",
  "kuching",
  "sungai petani",
  "muar",
  "bukit mertajam",
  "batu pahat",
  "kluang",
  "kuala langat",
  "temerloh",
  "nilai",
  "taiping",
  "alor setar",
  "sibu",
  "manjung",
  "kota bharu",
  "port dickson",
  "selayang",
  "bangkok",
  "samut prakan",
  "mueang nonthaburi",
  "udon thani",
  "chon buri",
  "nakhon ratchasima",
  "chiang mai",
  "hat yai",
  "ubon ratchathani",
  "pak kret",
  "khon kaen",
  "nakhon si thammarat",
  "nakhon pathom",
  "si racha",
  "phuket",
  "chiang rai",
  "lam luk ka",
  "nakhon sawan",
  "udon thani",
  "surat thani",
  "rayong",
  "nakhon ratchasima",
  "bang bua thong",
  "phra nakhon si ayutthaya",
  "min buri",
  "nong khaem",
  "lat phrao",
  "thon buri",
  "bang pho",
  "pattaya",
  "hua hin",
  "phitsanulok",
  "ratchathewi",
  "ho chi minh city",
  "hanoi",
  "haiphong",
  "can tho",
  "bien hoa",
  "hue",
  "nha trang",
  "buon ma thuot",
  "vung tau",
  "nam dinh",
  "qui nhon",
  "da lat",
  "long xuyen",
  "thai nguyen",
  "thanh hoa",
  "ha long",
  "cam ranh",
  "vinh",
  "my tho",
  "rach gia",
  "phan thiet",
  "cam pha",
  "vi thanh",
  "ha tien",
  "bac lieu",
  "jakarta",
  "surabaya",
  "medan",
  "bandung",
  "bekasi",
  "palembang",
  "tangerang",
  "makassar",
  "south tangerang",
  "depok",
  "semarang",
  "bogor",
  "batam",
  "pekanbaru",
  "bandar lampung",
  "padang",
  "malang",
  "denpasar",
  "samarinda",
  "tasikmalaya",
  "serang",
  "banjarmasin",
  "balikpapan",
  "pontianak",
  "cimahi",
  "sukabumi",
  "mataram",
  "jambi",
  "cirebon",
  "surakarta",
  "manado",
  "kupang",
  "yogyakarta",
  "ambon",
  "jayapura",
  "sorong",
  "ternate",
  "kendari",
  "palu",
  "banda aceh",
  "bengkulu",
  "manila",
  "quezon city",
  "caloocan",
  "davao city",
  "cebu city",
  "zamboanga city",
  "taguig",
  "antipolo",
  "pasig",
  "cagayan de oro",
  "paranaque",
  "dasmarinas",
  "valenzuela",
  "bacoor",
  "general santos",
  "las pinas",
  "makati",
  "san jose del monte",
  "muntinlupa",
  "angeles",
  "marikina",
  "olongapo",
  "iloilo city",
  "mandaue",
  "butuan",
  "tacloban",
  "navotas",
  "malabon",
  "dagupan",
  "naga",
  "ormoc",
  "santiago",
  "iligan",
  "lucena",
  "mandaue",
  "baguio",
  "lipa",
  "legazpi",
  "san fernando",
  "tanauan",
  "cabanatuan",
  "tuguegarao",
  "tarlac city",
  "malolos",
  "san pablo",
  "imus",
  "batangas city",
  "san mateo",
  "cauayan",
  "tabuk",
  "malaybalay",
  "koronadal",
  "kidapawan",
  "cotabato city",
  "digos",
  "panabo",
  "tagum",
  "mati",
  "catbalogan",
  "borongan",
  "maasin",
  "dumaguete",
  "bohol",
  "tagbilaran",
  "roxas",
  "kalibo",
  "iloilo",
  "bacolod",
  "san carlos",
  "kabankalan",
  "himamaylan",
  "cadiz",
  "sagay",
  "silay",
  "victorias",
  "talisay",
  "bago",
  "la carlota",
  "escalante",
  "manapla",
  "murcia",
  "don salvador benedicto",
  "calatrava",
  "toboso",
  "valladolid",
  "pulupandan",
  "san enrique",
  "pontevedra",
  "hinigaran",
  "binalbagan",
  "isabela",
  "moises padilla",
  "la castellana",
  "cauayan",
  "candoni",
  "ilog",
  "hinoba-an",
  "sydney",
  "melbourne",
  "brisbane",
  "perth",
  "adelaide",
  "gold coast",
  "canberra",
  "newcastle",
  "wollongong",
  "geelong",
  "hobart",
  "townsville",
  "cairns",
  "darwin",
  "toowoomba",
  "ballarat",
  "bendigo",
  "albury",
  "launceston",
  "mackay",
  "rockhampton",
  "bunbury",
  "bundaberg",
  "coffs harbour",
  "wagga wagga",
  "hervey bay",
  "mildura",
  "shepparton",
  "gladstone",
  "tamworth",
  "traralgon",
  "orange",
  "dubbo",
  "auckland",
  "wellington",
  "christchurch",
  "hamilton",
  "tauranga",
  "lower hutt",
  "dunedin",
  "palmerston north",
  "nelson",
  "rotorua",
  "new plymouth",
  "whangarei",
  "invercargill",
  "whanganui",
  "gisborne",
  "napier",
  "hastings",
  "upper hutt",
  "porirua",
  "kapiti",
  "masterton",
  "levin",
  "timaru",
  "oamaru",
  "blenheim",
  "greymouth",
  "westport",
  "hokitika",

  // Middle East & Africa
  "cairo",
  "alexandria",
  "giza",
  "shubra el kheima",
  "port said",
  "suez",
  "luxor",
  "al mahallah al kubra",
  "mansoura",
  "tanta",
  "asyut",
  "ismailia",
  "fayyum",
  "zagazig",
  "aswan",
  "damietta",
  "damanhur",
  "minya",
  "beni suef",
  "hurghada",
  "qena",
  "sohag",
  "shibin el kom",
  "banha",
  "arish",
  "mallawi",
  "10th of ramadan city",
  "bilbeis",
  "marsa matruh",
  "idfu",
  "mit ghamr",
  "al hamidiyya",
  "desouk",
  "qalyub",
  "abu kabir",
  "kafr el sheikh",
  "dikirnis",
  "kotor",
  "samannud",
  "talkha",
  "abu hammad",
  "kafr el dawwar",
  "girga",
  "akhmim",
  "matareya",
  "tel aviv",
  "jerusalem",
  "haifa",
  "rishon lezion",
  "petah tikva",
  "ashdod",
  "netanya",
  "beer sheva",
  "holon",
  "bnei brak",
  "ramat gan",
  "ashkelon",
  "rehovot",
  "bat yam",
  "beit shemesh",
  "kfar saba",
  "herzliya",
  "hadera",
  "modiin-maccabim-reut",
  "nazareth",
  "lod",
  "acre",
  "ramla",
  "tel aviv-yafo",
  "dubai",
  "abu dhabi",
  "sharjah",
  "al ain",
  "ajman",
  "ras al-khaimah",
  "fujairah",
  "umm al-quwain",
  "doha",
  "al rayyan",
  "al wakrah",
  "umm salal",
  "al khor",
  "al daayen",
  "muscat",
  "seeb",
  "salalah",
  "nizwa",
  "sur",
  "sohar",
  "rustaq",
  "bahla",
  "khasab",
  "al buraimi",
  "manama",
  "riffa",
  "muharraq",
  "hamad town",
  "a'ali",
  "isa town",
  "sitra",
  "budaiya",
  "jidhafs",
  "al-manamah",
  "kuwait city",
  "al ahmadi",
  "hawalli",
  "as salimiyah",
  "sabah as salim",
  "al farwaniyah",
  "al jahra",
  "riyadh",
  "jeddah",
  "mecca",
  "medina",
  "dammam",
  "khobar",
  "tabuk",
  "buraidah",
  "khamis mushait",
  "hail",
  "hofuf",
  "mubarraz",
  "taif",
  "jubail",
  "dhahran",
  "yanbu",
  "al qatif",
  "abha",
  "najran",
  "al kharj",
  "sakakah",
  "jizan",
  "arar",
  "al bahah",
  "amman",
  "zarqa",
  "irbid",
  "russeifa",
  "wadi as sir",
  "ajloun",
  "aqaba",
  "madaba",
  "salt",
  "mafraq",
  "jerash",
  "karak",
  "ma'an",
  "tafilah",
  "beirut",
  "tripoli",
  "sidon",
  "tyre",
  "nabatieh",
  "baalbek",
  "byblos",
  "zahle",
  "jounieh",
  "batroun",
  "damascus",
  "aleppo",
  "homs",
  "latakia",
  "hama",
  "deir ez-zor",
  "hasakah",
  "qamishli",
  "daraa",
  "al-suwayda",
  "tartus",
  "baghdad",
  "basra",
  "mosul",
  "erbil",
  "sulaymaniyah",
  "najaf",
  "karbala",
  "kirkuk",
  "tikrit",
  "ramadi",
  "fallujah",
  "dohuk",
  "samarra",
  "nasiriyah",
  "amarah",
  "kut",
  "baqubah",
  "zakho",
  "halabja",
  "sinjar",
  "tel afar",
  "qaim",
  "ana",
  "haditha",
  "tehran",
  "mashhad",
  "isfahan",
  "karaj",
  "shiraz",
  "tabriz",
  "qom",
  "ahvaz",
  "kermanshah",
  "urmia",
  "rasht",
  "zahedan",
  "kerman",
  "nazarabad",
  "yazd",
  "ardabil",
  "bandar abbas",
  "arak",
  "eslamshahr",
  "zanjan",
  "sanandaj",
  "qazvin",
  "khorramabad",
  "gorgan",
  "sari",
  "dezful",
  "bushehr",
  "qarchak",
  "varamin",
  "malard",
  "abadan",
  "borujen",
  "mahabad",
  "andimeshk",
  "bukan",
  "jiroft",
  "paveh",
  "khomeini shahr",
  "sabzevar",
  "khash",
  "sardasht",
  "javanrud",
  "borujerd",
  "iranian azerbaijan",
  "fars province",
  "khorasan",
  "khuzestan",
  "mazandaran",
  "east azerbaijan",
  "west azerbaijan",
  "kurdistan province",
  "hamadan province",
  "zanjan province",
  "qazvin province",
  "alborz province",
  "qom province",
  "markazi province",
  "lorestan province",
  "ilam province",
  "golestan province",
  "north khorasan",
  "razavi khorasan",
  "south khorasan",
  "semnan province",
  "yazd province",
  "kerman province",
  "hormozgan province",
  "sistan and baluchestan",
  "bushehr province",
  "kohgiluyeh and boyer-ahmad",
  "chaharmahal and bakhtiari",
  "johannesburg",
  "cape town",
  "durban",
  "pretoria",
  "soweto",
  "benoni",
  "tembisa",
  "pietermaritzburg",
  "welkom",
  "carletonville",
  "newcastle",
  "springs",
  "vanderbjlpark",
  "alberton",
  "randburg",
  "centurion",
  "mdantsane",
  "uitenhage",
  "roodepoort",
  "botshabelo",
  "brakpan",
  "witbank",
  "oberholzer",
  "germiston",
  "klerksdorp",
  "potchefstroom",
  "westonaria",
  "carletonville",
  "nigel",
  "delmas",
  "secunda",
  "sasolburg",
  "bethlehem",
  "kroonstad",
  "parys",
  "odendaalsrus",
  "heilbron",
  "vereeniging",
  "lagos",
  "kano",
  "ibadan",
  "abuja",
  "port harcourt",
  "benin city",
  "maiduguri",
  "zaria",
  "aba",
  "jos",
  "ilorin",
  "oyo",
  "enugu",
  "kaduna",
  "abeokuta",
  "onitsha",
  "warri",
  "sokoto",
  "ebute ikorodu",
  "okene",
  "calabar",
  "uyo",
  "katsina",
  "ado ekiti",
  "ogbomosho",
  "akure",
  "osogbo",
  "bauchi",
  "katsina-ala",
  "gusau",
  "minna",
  "owerri",
  "lafia",
  "umuahia",
  "ado-ekiti",
  "ikeja",
  "agege",
  "mushin",
  "oshodi",
  "ikeja",
  "maryland",
  "ikoyi",
  "victoria island",
  "lekki",
  "ajah",
  "badagry",
  "epe",
  "ikorodu",
  "alimosho",
  "ifako-ijaiye",
  "kosofe",
  "oshodi-isolo",
  "amuwo-odofin",
  "lagos mainland",
  "surulere",
  "apapa",
  "lagos island",
  "eti-osa",
  "nairobi",
  "mombasa",
  "kisumu",
  "nakuru",
  "eldoret",
  "kehancha",
  "ruiru",
  "kikuyu",
  "kangundo-tala",
  "malindi",
  "kitale",
  "garissa",
  "thika",
  "lamu",
  "isiolo",
  "narok",
  "moyale",
  "nyeri",
  "machakos",
  "meru",
  "kericho",
  "migori",
  "uasin gishu",
  "kakamega",
  "bungoma",
  "busia",
  "siaya",
  "kisii",
  "nyamira",
  "homa bay",
  "turkana",
  "west pokot",
  "samburu",
  "trans nzoia",
  "nandi",
  "baringo",
  "laikipia",
  "nyandarua",
  "kirinyaga",
  "murang'a",
  "kiambu",
  "addis ababa",
  "dire dawa",
  "mek'ele",
  "gondar",
  "awasa",
  "bahir dar",
  "dessie",
  "jimma",
  "jijiga",
  "shashamane",
  "nekemte",
  "bishoftu",
  "asosa",
  "harar",
  "kombolcha",
  "debre birhan",
  "arba minch",
  "hosaena",
  "dilla",
  "debre markos",
  "adigrat",
  "wukro",
  "shire",
  "axum",
  "lalibela",
  "sekota",
  "kobo",
  "weldiya",
  "alamata",
  "maychew",
  "korem",
  "abi adi",
  "adigrante",
  "may tsebri",
  "kampala",
  "gulu",
  "lira",
  "mbarara",
  "jinja",
  "bwizibwera",
  "mukono",
  "kasese",
  "masaka",
  "entebbe",
  "njeru",
  "kitgum",
  "mubende",
  "mityana",
  "lugazi",
  "wobulenzi",
  "iganga",
  "kayunga",
  "kamuli",
  "tororo",
  "soroti",
  "pallisa",
  "mbale",
  "butaleja",
  "budaka",
  "mayuge",
  "bugiri",
  "namutumba",
  "kaliro",
  "buyende",
  "dar es salaam",
  "mwanza",
  "arusha",
  "mbeya",
  "morogoro",
  "tanga",
  "kahama",
  "tabora",
  "zanzibar city",
  "kigoma",
  "sumbawanga",
  "kasulu",
  "musoma",
  "shinyanga",
  "iringa",
  "singida",
  "njombe",
  "bukoba",
  "mtwara",
  "mpanda",
  "dodoma",
  "kondoa",
  "babati",
  "moshi",
  "same",
  "korogwe",
  "handeni",
  "pangani",
  "tunduru",
  "newala",
  "masasi",
  "lindi",
  "kilifi",
  "malindi",
  "watamu",
  "mombasa",
  "kwale",
  "msambweni",
  "lunga lunga",
  "vanga",
  "shimoni",
  "casablanca",
  "rabat",
  "fez",
  "marrakech",
  "agadir",
  "tangier",
  "meknes",
  "oujda",
  "kenitra",
  "tetouan",
  "safi",
  "mohammedia",
  "khouribga",
  "el jadida",
  "beni mellal",
  "nador",
  "taza",
  "settat",
  "berrechid",
  "khenifra",
  "tiznit",
  "ouarzazate",
  "errachidia",
  "guelmim",
  "ksar el kebir",
  "sale",
  "larache",
  "khmissat",
  "berkane",
  "sidi kacem",
  "al hoceima",
  "taourirt",
  "al fqih ben salah",
  "boulemane",
  "tinghir",
  "sidi slimane",
  "youssoufia",
  "laayoune",
  "fnideq",
  "sefrou",
  "azrou",
  "midelt",
  "ifrane",
  "zaio",
  "jerada",
  "ahfir",
  "bouarfa",
  "figuig",
  "rich",
  "boumalne dades",
  "kalaat m'gouna",
  "zagora",
  "m'hamid el ghizlane",
  "erfoud",
  "rissani",
  "arfoud",
  "aoufous",
  "goulmima",
  "tinejdad",
  "jorf",
  "algiers",
  "oran",
  "constantine",
  "annaba",
  "blida",
  "batna",
  "djelfa",
  "setif",
  "sidi bel abbes",
  "biskra",
  "tebessa",
  "el oued",
  "skikda",
  "tiaret",
  "bejaia",
  "tlemcen",
  "ouargla",
  "mostaganem",
  "bordj bou arreridj",
  "chlef",
  "medea",
  "tizi ouzou",
  "el tarf",
  "jijel",
  "relizane",
  "mila",
  "ain beida",
  "mascara",
  "ouled djellal",
  "khenchela",
  "souk ahras",
  "el eulma",
  "ain oussera",
  "aflou",
  "tolga",
  "touggourt",
  "laghouat",
  "hassi messaoud",
  "ghardaia",
  "el menia",
  "metlili",
  "ouled nail",
  "ain salah",
  "idles",
  "timimoun",
  "adrar",
  "reggane",
  "in amenas",
  "illizi",
  "djanet",
  "tunis",
  "sfax",
  "sousse",
  "ettadhamen",
  "kairouan",
  "bizerte",
  "gabes",
  "aryanah",
  "la soukra",
  "gafsa",
  "el mourouj",
  "hammam lif",
  "ben arous",
  "denden",
  "nabeul",
  "hammam chott",
  "bardo",
  "le kram",
  "monastir",
  "mahdia",
  "tataouine",
  "medenine",
  "zarzis",
  "tozeur",
  "nefta",
  "douz",
  "kebili",
  "el hamma",
  "jemmal",
  "ksar hellal",
  "bekalta",
  "beni khalled",
  "soliman",
  "korba",
  "kelibia",
  "el haouaria",
  "tripoli",
  "benghazi",
  "misrata",
  "al bayda",
  "zawyah",
  "ajdabiya",
  "tobruk",
  "al marj",
  "derna",
  "gharyan",
  "nalut",
  "zliten",
  "bani walid",
  "tarhuna",
  "sirte",
  "sebha",
  "al kufra",
  "ghat",
  "murzuq",
  "awbari",
  "ubari",

  // South America
  "são paulo",
  "rio de janeiro",
  "brasília",
  "salvador",
  "fortaleza",
  "belo horizonte",
  "manaus",
  "curitiba",
  "recife",
  "goiânia",
  "belém",
  "porto alegre",
  "guarulhos",
  "campinas",
  "são luís",
  "são gonçalo",
  "maceió",
  "duque de caxias",
  "campo grande",
  "natal",
  "teresina",
  "são bernardo do campo",
  "nova iguaçu",
  "joão pessoa",
  "santo andré",
  "são josé dos campos",
  "jaboatão dos guararapes",
  "osasco",
  "ribeirão preto",
  "uberlândia",
  "sorocaba",
  "contagem",
  "aracaju",
  "feira de santana",
  "cuiabá",
  "joinville",
  "juiz de fora",
  "londrina",
  "aparecida de goiânia",
  "niterói",
  "campos dos goytacazes",
  "vila velha",
  "caxias do sul",
  "florianópolis",
  "serra",
  "pelotas",
  "betim",
  "diadema",
  "maringá",
  "jundiaí",
  "carapicuíba",
  "piracicaba",
  "cariacica",
  "bauru",
  "vitória",
  "são vicente",
  "franca",
  "canoas",
  "caucaia",
  "anápolis",
  "são josé do rio preto",
  "santos",
  "ribeirão das neves",
  "vitória da conquista",
  "santa maria",
  "vinhedo",
  "gravataí",
  "taboão da serra",
  "sumaré",
  "barueri",
  "embu das artes",
  "são caetano do sul",
  "mauá",
  "são josé dos pinhais",
  "itaquaquecetuba",
  "magé",
  "suzano",
  "são leopoldo",
  "marília",
  "são carlos",
  "governador valadares",
  "volta redonda",
  "taubaté",
  "praia grande",
  "foz do iguaçu",
  "limeira",
  "rio branco",
  "araraquara",
  "lages",
  "chapecó",
  "itapevi",
  "várzea grande",
  "americana",
  "novo hamburgo",
  "rio das ostras",
  "alvorada",
  "várzea paulista",
  "uberaba",
  "são josé",
  "cascavel",
  "petrolina",
  "rio grande",
  "santa luzia",
  "ferraz de vasconcelos",
  "são mateus",
  "presidente prudente",
  "francisco morato",
  "itapecerica da serra",
  "rio claro",
  "nova lima",
  "itu",
  "timon",
  "são caetano do sul",
  "franco da rocha",
  "são joão de meriti",
  "marabá",
  "blumenau",
  "passo fundo",
  "cotia",
  "santa bárbara d'oeste",
  "são josé de ribamar",
  "hortolândia",
  "indaiatuba",
  "são vicente",
  "itapetininga",
  "jacareí",
  "jandira",
  "jaú",
  "botucatu",
  "atibaia",
  "araçatuba",
  "toledo",
  "guarujá",
  "colombo",
  "são mateus do sul",
  "americana",
  "santa rita do sapucaí",
  "rio de janeiro",
  "buenos aires",
  "córdoba",
  "rosario",
  "mendoza",
  "tucumán",
  "la plata",
  "mar del plata",
  "salta",
  "santa fe",
  "san juan",
  "resistencia",
  "santiago del estero",
  "corrientes",
  "posadas",
  "bahía blanca",
  "paraná",
  "formosa",
  "neuquén",
  "san luis",
  "catamarca",
  "la rioja",
  "río cuarto",
  "comodoro rivadavia",
  "concordia",
  "san nicolás de los arroyos",
  "san rafael",
  "tandil",
  "villa mercedes",
  "san salvador de jujuy",
  "río gallegos",
  "ushuaia",
  "santa rosa",
  "san fernando del valle de catamarca",
  "la rioja",
  "rawson",
  "viedma",
  "santiago",
  "valparaíso",
  "concepción",
  "la serena",
  "antofagasta",
  "temuco",
  "rancagua",
  "talca",
  "arica",
  "chillán",
  "iquique",
  "los ángeles",
  "puerto montt",
  "calama",
  "coquimbo",
  "osorno",
  "valdivia",
  "quilpué",
  "villa alemana",
  "curicó",
  "punta arenas",
  "san antonio",
  "melipilla",
  "copiapó",
  "linares",
  "ovalle",
  "tarapacá",
  "la pintana",
  "puente alto",
  "maipú",
  "las condes",
  "providencia",
  "ñuñoa",
  "san bernardo",
  "peñalolén",
  "la florida",
  "quilicura",
  "pudahuel",
  "estación central",
  "lima",
  "arequipa",
  "callao",
  "trujillo",
  "chiclayo",
  "huancayo",
  "piura",
  "iquitos",
  "cusco",
  "chimbote",
  "tacna",
  "juliaca",
  "ica",
  "sullana",
  "ayacucho",
  "chincha alta",
  "huánuco",
  "tarapoto",
  "puno",
  "tumbes",
  "talara",
  "jaén",
  "ilo",
  "moquegua",
  "abancay",
  "cerro de pasco",
  "moyobamba",
  "puerto maldonado",
  "huaraz",
  "cajamarca",
  "pucallpa",
  "huacho",
  "catacaos",
  "lambayeque",
  "juanjuí",
  "bagua grande",
  "nueva cajamarca",
  "casma",
  "ferreñafe",
  "chocope",
  "paita",
  "sechura",
  "guadalupe",
  "pacasmayo",
  "bogotá",
  "medellín",
  "cali",
  "barranquilla",
  "cartagena",
  "cúcuta",
  "soledad",
  "ibagué",
  "bucaramanga",
  "soacha",
  "santa marta",
  "villavicencio",
  "valledupar",
  "pereira",
  "montería",
  "manizales",
  "pasto",
  "neiva",
  "palmira",
  "popayán",
  "buenaventura",
  "floridablanca",
  "turbaco",
  "malambo",
  "barrancas",
  "riohacha",
  "sincelejo",
  "tunja",
  "girón",
  "armenia",
  "itagüí",
  "envigado",
  "cartago",
  "apartadó",
  "facatativá",
  "zipaquirá",
  "fusagasugá",
  "duitama",
  "sogamoso",
  "chía",
  "madrid",
  "funza",
  "mosquera",
  "girardot",
  "bello",
  "copacabana",
  "sabaneta",
  "la estrella",
  "caldas",
  "barbosa",
  "rionegro",
  "caracas",
  "maracaibo",
  "valencia",
  "barquisimeto",
  "maracay",
  "ciudad guayana",
  "san cristóbal",
  "maturín",
  "ciudad bolívar",
  "cumana",
  "mérida",
  "barcelona",
  "turmero",
  "cabimas",
  "puerto la cruz",
  "los teques",
  "punto fijo",
  "guarenas",
  "acarigua",
  "petare",
  "araure",
  "barinas",
  "catia la mar",
  "el tigre",
  "pozuelos",
  "guacara",
  "san fernando de apure",
  "valle de la pascua",
  "carúpano",
  "villa de cura",
  "porlamar",
  "coro",
  "los altos",
  "quito",
  "guayaquil",
  "cuenca",
  "santo domingo",
  "ambato",
  "manta",
  "portoviejo",
  "machala",
  "loja",
  "riobamba",
  "esmeraldas",
  "ibarra",
  "milagro",
  "la libertad",
  "babahoyo",
  "quevedo",
  "tulcán",
  "pasaje",
  "santa elena",
  "nueva loja",
  "azogues",
  "macas",
  "puyo",
  "zamora",
  "tena",
  "guaranda",
  "latacunga",
  "san lorenzo",
  "otavalo",
  "salinas",
  "chone",
  "jipijapa",
  "bahía de caráquez",
  "calceta",
  "tosagua",
  "sucre",
  "el carmen",
  "ventanas",
  "valencia",
  "puebloviejo",
  "baba",
  "palenque",
  "vinces",
  "antonio ante",
  "cotacachi",
  "pimampiro",
  "urcuquí",
  "cayambe",
  "pedro moncayo",
  "mejía",
  "rumiñahui",
  "pedro vicente maldonado",
  "puerto quito",
  "san miguel de los bancos",
  "asunción",
  "ciudad del este",
  "san lorenzo",
  "luque",
  "capiatá",
  "lambaré",
  "fernando de la mora",
  "limpio",
  "nemby",
  "ñemby",
  "mariano roque alonso",
  "villa elisa",
  "san antonio",
  "itauguá",
  "areguá",
  "ypacaraí",
  "capiatá",
  "san bernardino",
  "altos",
  "tobatí",
  "coronel oviedo",
  "caaguazú",
  "villarrica",
  "paraguarí",
  "ybycuí",
  "sapucai",
  "la colmena",
  "mbuyapey",
  "acahay",
  "carapeguá",
  "quyquyhó",
  "uruguaiana",
  "montevideo",
  "salto",
  "paysandú",
  "las piedras",
  "rivera",
  "maldonado",
  "tacuarembó",
  "melo",
  "mercedes",
  "artigas",
  "minas",
  "san josé de mayo",
  "durazno",
  "florida",
  "rocha",
  "treinta y tres",
  "young",
  "fray bentos",
  "trinidad",
  "juan lacaze",
  "nueva palmira",
  "carmelo",
  "colonia del sacramento",
  "rosario",
  "tarariras",
  "nueva helvecia",
  "la paz",
  "santa cruz de la sierra",
  "el alto",
  "cochabamba",
  "oruro",
  "sucre",
  "tarija",
  "potosí",
  "sacaba",
  "quillacollo",
  "montero",
  "trinidad",
  "riberalta",
  "tiquipaya",
  "colcapirhua",
  "cobija",
  "yacuiba",
  "guayaramerín",
  "warnes",
  "llallagua",
  "camiri",
  "tupiza",
  "uyuni",
  "villazón",
  "bermejo",
  "puerto suárez",
  "san ignacio de moxos",
  "reyes",
  "rurrenabaque",
  "magdalena",
  "san borja",
  "santa ana del yacuma",
  "san ramón",
  "georgetown",
  "linden",
  "new amsterdam",
  "anna regina",
  "bartica",
  "rosignol",
  "skeldon",
  "springlands",
  "corriverton",
  "vreed en hoop",
  "parika",
  "mahaica",
  "paradise",
  "diamond",
  "la grange",
  "uitvlugt",
  "leonora",
  "wales",
  "parfaite harmonie",
  "paramaribo",
  "lelydorp",
  "brokopondo",
  "nieuw nickerie",
  "moengo",
  "albina",
  "groningen",
  "nieuwe amsterdam",
  "totness",
  "wageningen",
  "coronie",
  "cayenne",
  "saint-laurent-du-maroni",
  "kourou",
  "matoury",
  "rémire-montjoly",
  "macouria",
  "apatou",
  "grand-santi",
  "maripasoula",
  "saül",
  "camopi",
  "roura",
  "regina",
  "ouanary",
  "saint-élie",
  "iracoubo",
  "sinnamary",
  "mana",
  "awala-yalimapo",

  // North America - Canada
  "toronto",
  "montreal",
  "vancouver",
  "ottawa",
  "calgary",
  "edmonton",
  "quebec city",
  "winnipeg",
  "hamilton",
  "kitchener",
  "london",
  "st. catharines",
  "halifax",
  "oshawa",
  "victoria",
  "windsor",
  "saskatoon",
  "regina",
  "sherbrooke",
  "st. johns",
  "barrie",
  "kelowna",
  "abbotsford",
  "coquitlam",
  "trois-rivières",
  "guelph",
  "cambridge",
  "whitby",
  "ajax",
  "langley",
  "saanich",
  "terrebonne",
  "milton",
  "st-jean-sur-richelieu",
  "moncton",
  "thunder bay",
  "dieppe",
  "waterloo",
  "delta",
  "chatham",
  "red deer",
  "kamloops",
  "brantford",
  "cape breton",
  "lethbridge",
  "saint-jérôme",
  "belleville",
  "sarnia",
  "welland",
  "chilliwack",
  "châteauguay",
  "prince george",
  "drummondville",
  "saint-hyacinthe",
  "medicine hat",
  "granby",
  "saint-jean-sur-richelieu",
  "beloeil",
  "charlottetown",
  "fredericton",
  "penticton",
  "fort mcmurray",
  "north bay",
  "cornwall",
  "saint john",
  "port coquitlam",
  "joliette",
  "victoriaville",
  "woodstock",
  "aurora",
  "shawinigan",
  "dollard-des-ormeaux",
  "brandon",
  "rimouski",
  "saint-georges",
  "whitehorse",
  "yellowknife",
  "iqaluit",

  // Mexico
  "mexico city",
  "guadalajara",
  "puebla",
  "tijuana",
  "león",
  "juárez",
  "zapopan",
  "monterrey",
  "nezahualcóyotl",
  "chihuahua",
  "naucalpan",
  "mérida",
  "san luis potosí",
  "aguascalientes",
  "hermosillo",
  "saltillo",
  "mexicali",
  "culiacán",
  "guadalupe",
  "acapulco",
  "tlalnepantla",
  "cancún",
  "querétaro",
  "chimalhuacán",
  "torreón",
  "morelia",
  "reynosa",
  "tlaquepaque",
  "tuxtla gutiérrez",
  "victoria de durango",
  "toluca",
  "ciudad lópez mateos",
  "cuautitlán izcalli",
  "xalapa",
  "tonalá",
  "mazatlán",
  "apodaca",
  "general escobedo",
  "mérida",
  "ciudad apodaca",
  "veracruz",
  "irapuato",
  "ciudad guzmán",
  "tampico",
  "ensenada",
  "cuernavaca",
  "nuevo laredo",
  "pachuca",
  "oaxaca",
  "soledad de graciano sánchez",
  "san nicolás de los garza",
  "villahermosa",
  "ciudad obregón",
  "ecatepec",
  "la paz",
  "los mochis",
  "matamoros",
  "celaya",
  "ciudad valles",
  "metepec",
  "tapachula",
  "coatzacoalcos",
  "uruapan",
  "los cabos",
  "playa del carmen",
  "puerto vallarta",

  // Central America & Caribbean
  "guatemala city",
  "mixco",
  "villa nueva",
  "petapa",
  "san juan sacatepéquez",
  "quetzaltenango",
  "villa canales",
  "escuintla",
  "chinautla",
  "chimaltenango",
  "huehuetenango",
  "amatitlán",
  "totonicapán",
  "santa catarina pinula",
  "santa lucía cotzumalguapa",
  "puerto barrios",
  "san marcos",
  "antigua guatemala",
  "jalapa",
  "cobán",
  "san salvador",
  "soyapango",
  "santa ana",
  "san miguel",
  "mejicanos",
  "santa tecla",
  "apopa",
  "delgado",
  "ilopango",
  "san martín",
  "usulután",
  "cojutepeque",
  "zacatecoluca",
  "chalatenango",
  "ahuachapán",
  "sonsonate",
  "la unión",
  "tegucigalpa",
  "san pedro sula",
  "choloma",
  "la ceiba",
  "el progreso",
  "choluteca",
  "comayagua",
  "puerto cortés",
  "la lima",
  "danlí",
  "siguatepeque",
  "juticalpa",
  "catacamas",
  "tocoa",
  "tela",
  "olanchito",
  "managua",
  "león",
  "masaya",
  "chinandega",
  "matagalpa",
  "estelí",
  "granada",
  "jinotega",
  "nueva guinea",
  "boaco",
  "ocotal",
  "rivas",
  "juigalpa",
  "somoto",
  "san josé",
  "cartago",
  "puntarenas",
  "alajuela",
  "heredia",
  "limón",
  "desamparados",
  "san francisco",
  "goicoechea",
  "santa ana",
  "san isidro",
  "curridabat",
  "san carlos",
  "aserrí",
  "purral",
  "san rafael",
  "ipís",
  "san vicente",
  "san pablo",
  "mercedes",
  "san pedro",
  "san juan",
  "pavas",
  "hatillo",
  "san antonio",
  "escazú",
  "panama city",
  "san miguelito",
  "tocumen",
  "pedregal",
  "david",
  "arraijan",
  "colón",
  "las cumbres",
  "pacora",
  "chorrera",
  "parque lefevre",
  "río abajo",
  "puerto armuelles",
  "volcan",
  "chitré",
  "aguadulce",
  "santiago",
  "penonomé",
  "la chorrera",
  "vista alegre",
  "chepo",
  "capira",
  "chame",
  "san carlos",
  "havana",
  "santiago de cuba",
  "camagüey",
  "holguín",
  "santa clara",
  "guantánamo",
  "bayamo",
  "las tunas",
  "cienfuegos",
  "pinar del río",
  "matanzas",
  "ciego de ávila",
  "sancti spíritus",
  "manzanillo",
  "cardenas",
  "palma soriano",
  "contramaestre",
  "florida",
  "morón",
  "caibarién",
  "moa",
  "jamaica",
  "kingston",
  "spanish town",
  "portmore",
  "montego bay",
  "may pen",
  "mandeville",
  "old harbour",
  "savanna-la-mar",
  "negril",
  "port antonio",
  "linstead",
  "half way tree",
  "constant spring",
  "santo domingo",
  "santiago",
  "santo domingo este",
  "santo domingo norte",
  "san cristóbal",
  "puerto plata",
  "san pedro de macorís",
  "la romana",
  "san francisco de macorís",
  "higüey",
  "moca",
  "santiago rodríguez",
  "baní",
  "azua",
  "mao",
  "cotuí",
  "bonao",
  "san juan",
  "esperanza",
  "constanza",
  "jarabacoa",
  "port-au-prince",
  "cap-haïtien",
  "carrefour",
  "delmas",
  "gonaïves",
  "saint-marc",
  "les cayes",
  "pétionville",
  "jacmel",
  "fort-de-france",
  "le lamentin",
  "le robert",
  "sainte-marie",
  "ducos",
  "rivière-pilote",
  "saint-joseph",
  "la trinité",
  "le françois",
  "sainte-luce",
  "pointe-à-pitre",
  "les abymes",
  "baie-mahault",
  "le gosier",
  "petit-bourg",
  "sainte-anne",
  "le moule",
  "saint-françois",
  "capesterre-belle-eau",
  "saint-claude",

  // Major countries/regions/states
  "california",
  "florida",
  "texas",
  "new york state",
  "canada",
  "mexico",
  "united kingdom",
  "england",
  "scotland",
  "wales",
  "northern ireland",
  "ireland",
  "france",
  "germany",
  "italy",
  "spain",
  "netherlands",
  "holland",
  "belgium",
  "switzerland",
  "austria",
  "poland",
  "czech republic",
  "hungary",
  "sweden",
  "norway",
  "denmark",
  "finland",
  "russia",
  "turkey",
  "greece",
  "portugal",
  "romania",
  "bulgaria",
  "croatia",
  "serbia",
  "bosnia",
  "montenegro",
  "north macedonia",
  "albania",
  "slovenia",
  "slovakia",
  "estonia",
  "latvia",
  "lithuania",
  "belarus",
  "ukraine",
  "moldova",
  "iceland",
  "luxembourg",
  "malta",
  "cyprus",
  "andorra",
  "monaco",
  "vatican",
  "san marino",
  "liechtenstein",
  "china",
  "india",
  "indonesia",
  "pakistan",
  "bangladesh",
  "japan",
  "philippines",
  "vietnam",
  "turkey",
  "iran",
  "thailand",
  "myanmar",
  "south korea",
  "iraq",
  "afghanistan",
  "saudi arabia",
  "uzbekistan",
  "malaysia",
  "nepal",
  "yemen",
  "north korea",
  "sri lanka",
  "kazakhstan",
  "syria",
  "cambodia",
  "jordan",
  "azerbaijan",
  "united arab emirates",
  "tajikistan",
  "israel",
  "laos",
  "lebanon",
  "singapore",
  "oman",
  "kuwait",
  "georgia",
  "mongolia",
  "armenia",
  "qatar",
  "bahrain",
  "east timor",
  "palestine",
  "brunei",
  "bhutan",
  "maldives",
  "australia",
  "papua new guinea",
  "new zealand",
  "fiji",
  "solomon islands",
  "vanuatu",
  "samoa",
  "kiribati",
  "federated states of micronesia",
  "tonga",
  "palau",
  "marshall islands",
  "tuvalu",
  "nauru",
  "nigeria",
  "ethiopia",
  "egypt",
  "democratic republic of congo",
  "south africa",
  "kenya",
  "uganda",
  "algeria",
  "sudan",
  "morocco",
  "angola",
  "mozambique",
  "ghana",
  "madagascar",
  "cameroon",
  "côte d'ivoire",
  "niger",
  "burkina faso",
  "mali",
  "zambia",
  "somalia",
  "senegal",
  "zimbabwe",
  "chad",
  "south sudan",
  "guinea",
  "rwanda",
  "benin",
  "tunisia",
  "burundi",
  "togo",
  "sierra leone",
  "libya",
  "liberia",
  "central african republic",
  "mauritania",
  "eritrea",
  "gambia",
  "botswana",
  "namibia",
  "gabon",
  "lesotho",
  "guinea-bissau",
  "equatorial guinea",
  "mauritius",
  "eswatini",
  "djibouti",
  "comoros",
  "cape verde",
  "sao tome and principe",
  "seychelles",
  "brazil",
  "colombia",
  "argentina",
  "peru",
  "venezuela",
  "chile",
  "ecuador",
  "bolivia",
  "paraguay",
  "uruguay",
  "guyana",
  "suriname",
  "french guiana",

  // US States
  "alabama",
  "alaska",
  "arizona",
  "arkansas",
  "california",
  "colorado",
  "connecticut",
  "delaware",
  "florida",
  "georgia",
  "hawaii",
  "idaho",
  "illinois",
  "indiana",
  "iowa",
  "kansas",
  "kentucky",
  "louisiana",
  "maine",
  "maryland",
  "massachusetts",
  "michigan",
  "minnesota",
  "mississippi",
  "missouri",
  "montana",
  "nebraska",
  "nevada",
  "new hampshire",
  "new jersey",
  "new mexico",
  "new york",
  "north carolina",
  "north dakota",
  "ohio",
  "oklahoma",
  "oregon",
  "pennsylvania",
  "rhode island",
  "south carolina",
  "south dakota",
  "tennessee",
  "texas",
  "utah",
  "vermont",
  "virginia",
  "washington",
  "west virginia",
  "wisconsin",
  "wyoming",
  "district of columbia",
  "puerto rico",

  // Canadian Provinces/Territories
  "ontario",
  "quebec",
  "british columbia",
  "alberta",
  "manitoba",
  "saskatchewan",
  "nova scotia",
  "new brunswick",
  "newfoundland and labrador",
  "prince edward island",
  "northwest territories",
  "nunavut",
  "yukon",

  // Continents
  "north america",
  "south america",
  "europe",
  "asia",
  "africa",
  "antarctica",
  "oceania",
  "australia",

  // Regions
  "middle east",
  "central america",
  "caribbean",
  "scandinavia",
  "balkans",
  "eastern europe",
  "western europe",
  "central europe",
  "northern europe",
  "southern europe",
  "southeast asia",
  "east asia",
  "south asia",
  "central asia",
  "west asia",
  "north africa",
  "sub-saharan africa",
  "east africa",
  "west africa",
  "central africa",
  "southern africa",
];
